# Generated by Django 3.0.2 on 2020-01-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_profile_model_fac_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile_model',
            name='total_lecures',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
