# Generated by Django 3.0.2 on 2020-01-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_profile_model_total_lecures'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile_model',
            name='fac_file1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='faculty_profile_model',
            name='fac_file_name1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='faculty_profile_model',
            name='fac_file_name2',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
