# Generated by Django 3.0.2 on 2020-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20200130_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile_model',
            name='fac_file2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
