# Generated by Django 3.0.2 on 2020-02-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_faculty_profile_model_fac_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_profile_model',
            name='fac_file1',
        ),
        migrations.RemoveField(
            model_name='faculty_profile_model',
            name='fac_file2',
        ),
        migrations.RemoveField(
            model_name='faculty_profile_model',
            name='fac_file_name1',
        ),
        migrations.RemoveField(
            model_name='faculty_profile_model',
            name='fac_file_name2',
        ),
    ]
