# Generated by Django 3.0.2 on 2020-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_profile_model',
            name='std_password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
