# Generated by Django 3.0.2 on 2020-01-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student1', '0002_students_profile_model_std_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_profile_model',
            name='s1_sem1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s1_tt1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s1_tt2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s2_sem1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s2_tt1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s2_tt2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s3_sem1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s3_tt1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s3_tt2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s4_sem1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s4_tt1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s4_tt2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s5_sem1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s5_tt1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s5_tt2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s6_sem1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s6_tt1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='s6_tt2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='students_profile_model',
            name='std_dob',
            field=models.DateField(null=True),
        ),
    ]
